version: '3'

services:
  client:
    image: task-dispenser-client
    container_name: tds_client
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_BASE_API_URL=http://localhost:8080/